/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

/**
 *
 * @author Familia-Lima
 */
public class CertificadoImprimir extends javax.swing.JFrame {

    /**
     * Creates new form Certificado
     */
    public CertificadoImprimir() {
        initComponents();
    }
    
    public void setAtributes(int evento_id, int participante_id, String evento, 
                             String participante, String horas, String instituição,
                             String md5_hash){
        
        Jevento.setText(evento);
        Jparticipante.setText(participante);
        Jhoras.setText(horas);
        Jinstituicao.setText(instituição);
        Jhash.setText(md5_hash);
        
        
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fechar = new javax.swing.JButton();
        Jhash = new javax.swing.JLabel();
        Jinstituicao = new javax.swing.JLabel();
        Jparticipante = new javax.swing.JLabel();
        Jhoras = new javax.swing.JLabel();
        Jlogo = new javax.swing.JLabel();
        Jlogotipo = new javax.swing.JLabel();
        Jevento = new javax.swing.JLabel();
        Jcorpo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 488));
        getContentPane().setLayout(null);

        Fechar.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        Fechar.setForeground(new java.awt.Color(0, 0, 0));
        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        getContentPane().add(Fechar);
        Fechar.setBounds(90, 435, 80, 30);

        Jhash.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        Jhash.setForeground(new java.awt.Color(0, 0, 0));
        Jhash.setText("-");
        getContentPane().add(Jhash);
        Jhash.setBounds(420, 430, 200, 20);
        getContentPane().add(Jinstituicao);
        Jinstituicao.setBounds(170, 290, 180, 20);
        getContentPane().add(Jparticipante);
        Jparticipante.setBounds(230, 210, 380, 20);
        getContentPane().add(Jhoras);
        Jhoras.setBounds(520, 290, 30, 30);

        Jlogo.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Jlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.png"))); // NOI18N
        Jlogo.setText("Equipe Porta Lateral");
        getContentPane().add(Jlogo);
        Jlogo.setBounds(230, 30, 260, 70);

        Jlogotipo.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Jlogotipo.setText(" . . Facilitando sua Vida . .");
        getContentPane().add(Jlogotipo);
        Jlogotipo.setBounds(240, 90, 250, 30);
        getContentPane().add(Jevento);
        Jevento.setBounds(260, 245, 350, 30);

        Jcorpo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Familia-Lima\\Documents\\NetBeansProjects\\Projeto_lab_prog_2017-master\\src\\imagens\\certificadoa.jpg")); // NOI18N
        Jcorpo.setMaximumSize(new java.awt.Dimension(710, 500));
        Jcorpo.setMinimumSize(new java.awt.Dimension(710, 500));
        getContentPane().add(Jcorpo);
        Jcorpo.setBounds(0, 0, 700, 490);

        setSize(new java.awt.Dimension(716, 527));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        dispose();
    }//GEN-LAST:event_FecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CertificadoImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CertificadoImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CertificadoImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CertificadoImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CertificadoImprimir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fechar;
    private javax.swing.JLabel Jcorpo;
    private javax.swing.JLabel Jevento;
    private javax.swing.JLabel Jhash;
    private javax.swing.JLabel Jhoras;
    private javax.swing.JLabel Jinstituicao;
    private javax.swing.JLabel Jlogo;
    private javax.swing.JLabel Jlogotipo;
    private javax.swing.JLabel Jparticipante;
    // End of variables declaration//GEN-END:variables
}
