/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.HashSet;
import visao.Telalogin;

/**
 *
 * @author Esther & Marciel
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalvar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelNomeRazão = new javax.swing.JLabel();
        jTextFieldNomeRazão = new javax.swing.JTextField();
        jLabelCpfCnpj = new javax.swing.JLabel();
        jTextFieldCPFcnpj = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelConfirmarEmail = new javax.swing.JLabel();
        jTextFieldConfirmarEmail = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelConfirmarSenha = new javax.swing.JLabel();
        jPasswordFieldConfirmarSenha = new javax.swing.JPasswordField();
        jCheckBoxTermosdeUso = new javax.swing.JCheckBox();
        jLabelPlanodeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonSalvar.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jButtonSalvar.setText("SALVAR");
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(110, 420, 120, 40);

        jButtonVoltar.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jButtonVoltar.setText("SAIR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(240, 420, 120, 40);

        jLabelUsuario.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuário");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(210, 30, 50, 14);
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(120, 50, 230, 30);

        jLabelNomeRazão.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabelNomeRazão.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeRazão.setText("Nome / Razão Social");
        getContentPane().add(jLabelNomeRazão);
        jLabelNomeRazão.setBounds(180, 80, 120, 14);
        getContentPane().add(jTextFieldNomeRazão);
        jTextFieldNomeRazão.setBounds(120, 100, 230, 30);

        jLabelCpfCnpj.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabelCpfCnpj.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCpfCnpj.setText("CPF / CNPJ");
        getContentPane().add(jLabelCpfCnpj);
        jLabelCpfCnpj.setBounds(210, 130, 70, 15);
        getContentPane().add(jTextFieldCPFcnpj);
        jTextFieldCPFcnpj.setBounds(120, 150, 230, 30);

        jLabelEmail.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("E-mail");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(220, 180, 40, 15);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(120, 200, 230, 30);

        jLabelConfirmarEmail.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabelConfirmarEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConfirmarEmail.setText("Confirmar E-mail");
        getContentPane().add(jLabelConfirmarEmail);
        jLabelConfirmarEmail.setBounds(190, 230, 100, 14);
        getContentPane().add(jTextFieldConfirmarEmail);
        jTextFieldConfirmarEmail.setBounds(120, 250, 230, 30);

        jLabelSenha.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(220, 280, 40, 15);
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(120, 300, 230, 30);

        jLabelConfirmarSenha.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabelConfirmarSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConfirmarSenha.setText("Confirmar Senha");
        getContentPane().add(jLabelConfirmarSenha);
        jLabelConfirmarSenha.setBounds(180, 331, 100, 14);
        getContentPane().add(jPasswordFieldConfirmarSenha);
        jPasswordFieldConfirmarSenha.setBounds(120, 350, 230, 30);

        jCheckBoxTermosdeUso.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jCheckBoxTermosdeUso.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxTermosdeUso.setText("Aceito os termos de uso e privacidade.");
        jCheckBoxTermosdeUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTermosdeUsoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxTermosdeUso);
        jCheckBoxTermosdeUso.setBounds(110, 390, 250, 22);

        jLabelPlanodeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/porta.jpg"))); // NOI18N
        getContentPane().add(jLabelPlanodeFundo);
        jLabelPlanodeFundo.setBounds(0, 0, 470, 494);

        setSize(new java.awt.Dimension(490, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
    dispose();
        
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jCheckBoxTermosdeUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTermosdeUsoActionPerformed
       // Acao do checkbox que confirma aceite dos termmos de uso do sistema
    }//GEN-LAST:event_jCheckBoxTermosdeUsoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBoxTermosdeUso;
    private javax.swing.JLabel jLabelConfirmarEmail;
    private javax.swing.JLabel jLabelConfirmarSenha;
    private javax.swing.JLabel jLabelCpfCnpj;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNomeRazão;
    private javax.swing.JLabel jLabelPlanodeFundo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldCPFcnpj;
    private javax.swing.JTextField jTextFieldConfirmarEmail;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNomeRazão;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
