/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Esther & Marciel
 */
public class DashboardUser extends javax.swing.JFrame {

    /**
     * Creates new form DashboardUser
     */
    public DashboardUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabelPlanodeFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemUsuarioNovo = new javax.swing.JMenuItem();
        jMenuItemUsuarioExcluir = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuEventos = new javax.swing.JMenu();
        jMenuItemEventosNovo = new javax.swing.JMenuItem();
        jMenuItemEventosExcluir = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuCertificados = new javax.swing.JMenu();
        jMenuItemCertificadosNovo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemCertificadosExcluir = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarUsuario = new javax.swing.JMenuItem();
        jMenuItemPesquisarEventos = new javax.swing.JMenuItem();
        jMenuItemPesquisarCertificados = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemAjudaSobre = new javax.swing.JMenuItem();
        jMenuItemAjudaContatos = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAjudaSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Termos de Uso ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 400, 120, 40);

        jLabelPlanodeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg6a.jpg"))); // NOI18N
        getContentPane().add(jLabelPlanodeFundo);
        jLabelPlanodeFundo.setBounds(0, -20, 800, 470);

        jMenuUsuarios.setText("Usuários");

        jMenuItemUsuarioNovo.setText("Criar novo");
        jMenuItemUsuarioNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioNovoActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUsuarioNovo);

        jMenuItemUsuarioExcluir.setText("Excluir");
        jMenuItemUsuarioExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioExcluirActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUsuarioExcluir);
        jMenuUsuarios.add(jSeparator2);

        jMenuBar1.add(jMenuUsuarios);

        jMenuEventos.setText("Eventos");

        jMenuItemEventosNovo.setText("Criar novo");
        jMenuItemEventosNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEventosNovoActionPerformed(evt);
            }
        });
        jMenuEventos.add(jMenuItemEventosNovo);

        jMenuItemEventosExcluir.setText("Excluir");
        jMenuItemEventosExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEventosExcluirActionPerformed(evt);
            }
        });
        jMenuEventos.add(jMenuItemEventosExcluir);
        jMenuEventos.add(jSeparator3);

        jMenuBar1.add(jMenuEventos);

        jMenuCertificados.setText("Certificados");

        jMenuItemCertificadosNovo.setText("Cadastrar Participante");
        jMenuItemCertificadosNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCertificadosNovoActionPerformed(evt);
            }
        });
        jMenuCertificados.add(jMenuItemCertificadosNovo);

        jMenuItem1.setText("Emitir CERTIFICADOS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCertificados.add(jMenuItem1);

        jMenuItemCertificadosExcluir.setText("Excluir");
        jMenuItemCertificadosExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCertificadosExcluirActionPerformed(evt);
            }
        });
        jMenuCertificados.add(jMenuItemCertificadosExcluir);
        jMenuCertificados.add(jSeparator4);

        jMenuBar1.add(jMenuCertificados);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarUsuario.setText("Usuários");
        jMenuPesquisar.add(jMenuItemPesquisarUsuario);

        jMenuItemPesquisarEventos.setText("Eventos");
        jMenuPesquisar.add(jMenuItemPesquisarEventos);

        jMenuItemPesquisarCertificados.setText("Certificados");
        jMenuPesquisar.add(jMenuItemPesquisarCertificados);

        jMenuBar1.add(jMenuPesquisar);

        jMenuAjuda.setText("Ajuda");
        jMenuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAjudaActionPerformed(evt);
            }
        });

        jMenuItemAjudaSobre.setText("Sobre");
        jMenuItemAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAjudaSobre);

        jMenuItemAjudaContatos.setText("Contatos");
        jMenuItemAjudaContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaContatosActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAjudaContatos);
        jMenuAjuda.add(jSeparator6);
        jMenuAjuda.add(jSeparator5);

        jMenuItemAjudaSair.setText("Sair");
        jMenuItemAjudaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaSairActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAjudaSair);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(818, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAjudaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaSairActionPerformed
        TelaPrincipal sair = new TelaPrincipal();
        sair.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemAjudaSairActionPerformed

    private void jMenuItemUsuarioNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioNovoActionPerformed
     CadastroUsuario novo = new CadastroUsuario();
     novo.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioNovoActionPerformed

    private void jMenuItemAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaSobreActionPerformed
        Versao sobre = new Versao();
        sobre.setVisible(true);
    }//GEN-LAST:event_jMenuItemAjudaSobreActionPerformed

    private void jMenuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAjudaActionPerformed


    }//GEN-LAST:event_jMenuAjudaActionPerformed

    private void jMenuItemAjudaContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaContatosActionPerformed
    Contatos contato = new Contatos();
    contato.setVisible(true);
    }//GEN-LAST:event_jMenuItemAjudaContatosActionPerformed

    private void jMenuItemCertificadosNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCertificadosNovoActionPerformed
        CadastroParticipante novo = new CadastroParticipante();
        novo.setVisible(true);
    }//GEN-LAST:event_jMenuItemCertificadosNovoActionPerformed

    private void jMenuItemUsuarioExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioExcluirActionPerformed
        // Excluir usuario ...
    }//GEN-LAST:event_jMenuItemUsuarioExcluirActionPerformed

    private void jMenuItemEventosExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEventosExcluirActionPerformed
        // Excluir eventos .....  
    }//GEN-LAST:event_jMenuItemEventosExcluirActionPerformed

    private void jMenuItemEventosNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEventosNovoActionPerformed
    CadastroEventos eventos = new CadastroEventos();
    eventos.setVisible(true);
    }//GEN-LAST:event_jMenuItemEventosNovoActionPerformed

    private void jMenuItemCertificadosExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCertificadosExcluirActionPerformed
       // Excuir participante ha receber certificado
    }//GEN-LAST:event_jMenuItemCertificadosExcluirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Emitir certificados aqui
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Termos t = new Termos();
        t.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelPlanodeFundo;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCertificados;
    private javax.swing.JMenu jMenuEventos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAjudaContatos;
    private javax.swing.JMenuItem jMenuItemAjudaSair;
    private javax.swing.JMenuItem jMenuItemAjudaSobre;
    private javax.swing.JMenuItem jMenuItemCertificadosExcluir;
    private javax.swing.JMenuItem jMenuItemCertificadosNovo;
    private javax.swing.JMenuItem jMenuItemEventosExcluir;
    private javax.swing.JMenuItem jMenuItemEventosNovo;
    private javax.swing.JMenuItem jMenuItemPesquisarCertificados;
    private javax.swing.JMenuItem jMenuItemPesquisarEventos;
    private javax.swing.JMenuItem jMenuItemPesquisarUsuario;
    private javax.swing.JMenuItem jMenuItemUsuarioExcluir;
    private javax.swing.JMenuItem jMenuItemUsuarioNovo;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
