/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Familia-Lima
 */
public class ExcluirUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirUsuario
     */
    public ExcluirUsuario() {
        initComponents();
        this.Atualizar.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sair = new javax.swing.JButton();
        Apagar = new javax.swing.JButton();
        IDUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Atualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Usuarios = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Sair.setText("SAIR");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(158, 450, 140, 25);

        Apagar.setText("APAGAR");
        Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarActionPerformed(evt);
            }
        });
        getContentPane().add(Apagar);
        Apagar.setBounds(353, 410, 80, 30);
        getContentPane().add(IDUsuario);
        IDUsuario.setBounds(110, 410, 240, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escolha o ID do Usuario Para Apagar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 100, 350, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID =");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 410, 30, 30);

        Atualizar.setText("Atualizar Lista");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Atualizar);
        Atualizar.setBounds(300, 450, 130, 25);

        Usuarios.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jScrollPane1.setViewportView(Usuarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 420, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/porta.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 500);

        setSize(new java.awt.Dimension(488, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        dispose();

    }//GEN-LAST:event_SairActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed

           BancoDeDados database = new BancoDeDados();
           database.configurar_connection("root","","porta");
           DefaultListModel dataModel = new DefaultListModel();
           
           String linha_dados = new String();
           
           try {
               
                ResultSet resultados = database.buscarUsuarios();
                
                while (resultados.next()) {
                    
                    linha_dados = String.valueOf(resultados.getString("id"));
                    linha_dados += " - ";
                    linha_dados += String.valueOf(resultados.getString("user"));
                    linha_dados += " - ";
                    linha_dados += String.valueOf(resultados.getString("email"));
                    dataModel.addElement(linha_dados);
                                     
                    
                }
               
           } catch (SQLException exception) {
               
               System.out.println("Zikou");
               
           }
           Usuarios.setModel(dataModel);
                    
          Usuarios.repaint();
    }//GEN-LAST:event_AtualizarActionPerformed

    private void ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarActionPerformed
        
           BancoDeDados database = new BancoDeDados();
           database.configurar_connection("root","","porta");         
           
           if (database.removerUsuario(Integer.parseInt(IDUsuario.getText()))) {
               
               JOptionPane.showMessageDialog(null, "usuário removido");
               this.Atualizar.doClick(); 
               Usuarios.repaint();
               
           } else {
               
               JOptionPane.showMessageDialog(null, "não foi possível remover o usuário");
               
           };
          
        
    }//GEN-LAST:event_ApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagar;
    private javax.swing.JButton Atualizar;
    private javax.swing.JTextField IDUsuario;
    private javax.swing.JButton Sair;
    private javax.swing.JList<String> Usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
