/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;

/**
 *
 * @author Familia-Lima
 */
public class PesquisarEventos extends javax.swing.JFrame {

    /**
     * Creates new form PesquisarEventos
     */
    public PesquisarEventos() {
        initComponents();
        Atualizar.doClick();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeEvento = new javax.swing.JTextField();
        Pesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListarEventos = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        Atualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(NomeEvento);
        NomeEvento.setBounds(90, 170, 230, 40);

        Pesquisar.setText("PESQUISAR");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(Pesquisar);
        Pesquisar.setBounds(330, 170, 100, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 170, 60, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pesquisa de Eventos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 110, 190, 40);

        Sair.setText("SAIR");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(340, 420, 120, 40);

        ListarEventos.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        ListarEventos.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(ListarEventos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 450, 170);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LISTA DE EVENTOS GRAVADOS NO SISTEMA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 220, 290, 20);

        Atualizar.setText("ATUALIZAR");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Atualizar);
        Atualizar.setBounds(10, 420, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/porta.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 500);

        setSize(new java.awt.Dimension(488, 532));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        // efetuar conexão com o banco de dados

        BancoDeDados database = new BancoDeDados();
        database.configurar_connection("root", "atbiotec2013", "porta");

        // receber nome do evento
        String nome = NomeEvento.getText();

        // lista de certificados
        DefaultListModel dataModel = new DefaultListModel();

        // variáveis que guarda cada linha
        String evento = new String();
        String instituição = new String();

        String dataLine = new String();

        try {

            ResultSet resultadoEventos = database.buscarEventos(nome);

            while (resultadoEventos.next()) {

                evento = resultadoEventos.getString("nome");
                instituição = resultadoEventos.getString("instituicao");

                dataLine = evento;
                dataLine += " - ";
                dataLine += instituição;
                dataModel.addElement(dataLine);

            }

            ListarEventos.setModel(dataModel);
            ListarEventos.repaint();

        } catch (SQLException exception) {

            System.out.println("zikou");
            System.out.println(exception.getMessage());
        }


    }//GEN-LAST:event_PesquisarActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed

        BancoDeDados database = new BancoDeDados();
        database.configurar_connection("root", "", "porta");
        DefaultListModel dataModel = new DefaultListModel();

        String linha_dados = new String();

        try {

            ResultSet resultados = database.buscarEventos();

            while (resultados.next()) {

                linha_dados = String.valueOf(resultados.getString("id"));
                linha_dados += " - ";
                linha_dados += String.valueOf(resultados.getString("nome"));
                linha_dados += " - ";
                linha_dados += String.valueOf(resultados.getString("instituicao"));
                dataModel.addElement(linha_dados);

            }

        } catch (SQLException exception) {

            System.out.println("Zikou");

        }

        ListarEventos.setModel(dataModel);
        ListarEventos.repaint();

    }//GEN-LAST:event_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JList<String> ListarEventos;
    private javax.swing.JTextField NomeEvento;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
